name: Lighthouse CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      # Add any runtime env so your SSR routes don’t 302 to login:
      # NEXT_PUBLIC_API_BASE: ${{ secrets.NEXT_PUBLIC_API_BASE }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - run: yarn --version  # sanity check
      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v11
        with:
          lhci_command: autorun
          config_path: "./lighthouserc.json"

      - name: Upload Lighthouse reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports-${{ github.run_id }}
          path: |
            .lighthouseci/*.html
            .lighthouseci/*.json
          retention-days: 7
