name: 'Lighthouse CI'
on: [pull_request]
jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Serve production build
        run: |
          npm install -g http-server
          http-server ./build -p 8080 &
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          lhci_command: autorun
          config_path: './lighthouserc.json'
